### ISSUE TITLE
fix installation description

### ISSUE THREAD

**Issue by snoopy0815** [evilmarty/mjpeg-timelapse#1]
nice addon - thanks for sharing!

in the installation-steps - point 3) seems to have a copy&paste error:
   3) In the custom_components directory create a new directory called audiconnect.

obviously audioconnect should be renamed to mjpeg_timelapse

and by the way: HACS can't find this at all - unfortunately :(

cheers.

**Comment by evilmarty** [comment]
Thanks for the heads up. I'll take a look.
