### ISSUE TITLE
Setting to record for 24 hours doesn't seem to work

### ISSUE THREAD

**Issue by robertboccia** [evilmarty/mjpeg-timelapse#10]
I have left the default fetch interval at 60 and set  max frames to 2500 but it doesn't record for 24 hours, am I missing something?

**Comment by evilmarty** [comment]
Do you mean to say that you're trying to capture an image once per day and it's not doing that? If so are there any errors in the logs?

**Comment by robertboccia** [comment]
> Do you mean to say that you're trying to capture an image once per day and it's not doing that? If so are there any errors in the logs?

No I'm trying record for a full 24 hours or better yet 7 days like a normal nvrwould do

**Comment by evilmarty** [comment]
So your intention is to capture 60 frames per hour (1440 frames) for a maximum of 7 days (10080 frames). How many frames are being captured?

**Comment by robertboccia** [comment]
Seems to stop after a few hours

**Comment by robertboccia** [comment]
I started with 24 hours but doesn't seem to capture 24 hours when I click on the playback only seems to go back to a few hours

**Comment by robertboccia** [comment]
Also once setup there is no way to edit it would seem?

**Comment by evilmarty** [comment]
Not at this stage. It's a completely different implementation to edit/change an entry. 

What are the inputs that you've entered?

**Comment by robertboccia** [comment]
Currently set to 2500 frames,  but when you click on the entity only seems to playback for a few hours and not go back to the start of the recording?

**Comment by robertboccia** [comment]
So I see the camera folder seems to have the right amounts of captures, but the image playback doesn't run through them all for some reason seems to stop and reset playback half way through, any ideas as to why?

**Comment by evilmarty** [comment]
I don't see how as the [code is fetching all JPGs in the folder](https://github.com/evilmarty/mjpeg-timelapse/blob/main/custom_components/mjpeg_timelapse/camera.py#L334).

**Comment by robertboccia** [comment]
May be fetching them but doesn't play them all stops mid way through and then jumps to the first one again

**Comment by bcutter** [comment]
Can we please reopen? The recording works fine, but the play stops after a certain amount of images.
