### ISSUE TITLE
Trigger image capture at certain times of day

### ISSUE THREAD

**Issue by markaggar** [evilmarty/mjpeg-timelapse#11]
I'm trying to build a timelapse which captures an image per day across a year or so.  I want the capture to happen at the same time each day (around noon).  However, I can only specify an interval, which is reset each time HA restarts.  Therefore, and day that I restart HA, I don't get an image capture, and I get an image 24 hours later, which is going to be at a different time than I wouuld like.

So the feature request is to be able to specify an optional time of day for the image to be captured.

Tx!

**Comment by evilmarty** [comment]
You're welcome to submit a PR for such a feature.
