### ISSUE TITLE
Integration will fail in 2023.2

### ISSUE THREAD

**Issue by jex276** [evilmarty/mjpeg-timelapse#17]
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for mjpeg_timelapse using this method at custom_components/mjpeg_timelapse/__init__

**Comment by evilmarty** [comment]
This issue has little to no detail and is unhelpful. Closing.

**Comment by jex276** [comment]
Showing that something will stop working this month is unhelpful?...ok

**Comment by evilmarty** [comment]
No, it is not. There's no detail nor context. Just a copy and paste and nothing else. You may think that you are being helpful but I am telling you that it was not.
