### ISSUE TITLE
add possibility for webcam with username and password

### ISSUE THREAD

**Issue by snoopy0815** [evilmarty/mjpeg-timelapse#3]
finally I've got it running - after finding the error on my side - I've forgotten that my camera requests username and password...
after switching this off for testing - it works like a charm :) 

therefor this feature-request:
would it be possible to either enhance this wonderful extension to handle cameras with username and passwords
or
except as input just the camera entity, which is already present within the configuration.yaml ?

e.g. I have multiple motioneye streams already present like this - would be perfect if this timelaps extension could be feed with the name "Terrasse"

```
  - platform: mjpeg
    name: Terrasse
    mjpeg_url: http://192.168.178.44:8081
    username: xxxx
    password: yyyy
    authentication: digest
    
```

I would be more than happy to test or support in any way - unfortunately me skills are not sufficient to suggest a pull-request right away :(
(I could even not find out, where the timelapse pictures are stored - maybe this could be as well a helpful info for unexperienced user in order to delete maybe later on some of them - or start debugging)

cheers! and thanks once again!

**Comment by evilmarty** [comment]
> I could even not find out, where the timelapse pictures are stored

They are stored in your HA config directory in a folder called `camera`.

**Comment by Trebacz** [comment]
My cameras (Reolink) allow passing user name and password in the query string. I set up view only guest camera accounts and access through https... This works more my setup. Thought it may help you.

**Comment by Electronlibre2012** [comment]
hello @evilmarty 

thanks a lot for your work, nice feature.

I search for minutes where the pictures are stored...found them, but i dont understand where the mpeg video is and how stop the time laps...
sorry if its a nooby question but dont found any info about this, anymwhere...

Thanks

**Comment by evilmarty** [comment]
@Electronlibre2012 you're welcome.

> but i dont understand where the mpeg video is?
There are no videos being generated. It's using M**J**PEG, not MPEG. They are different formats.

> i would like to create in /media folder and then i can reach "camera"
If you'd like the `camera` folder in the `/media` folder you can just create a symlink.
