### ISSUE TITLE
Event timelapse

### ISSUE THREAD

**Issue by proutska** [evilmarty/mjpeg-timelapse#9]
Hi, thanks for this great integration. Could it be possible to add a service to trigger the recordings instead of time based recording? The result will be a timelapse video of all the events during a certain period. This way I can view a short video of all the events that happend in my garden during the day.

Thanks in advance,

Sander

**Comment by evilmarty** [comment]
There are two service calls you can use to pause and resume recording. So you can create your own automations to control this.
